import{useCallback,useEffect,useMemo,useRef,useState}from"react";import{Navigation,LocateFixed,Search,AlertTriangle,Route as RouteIcon,X,MapPin,Clock3,CarFront,Wifi,WifiOff,Volume2,VolumeX,ChevronDown}from"lucide-react";import maplibregl from"maplibre-gl";

type Point={lat:number;lon:number;name?:string};type Report={id:string;lat:number;lon:number;type:string;note:string;time:number};
const IRAQ=[44.0,33.2] as [number,number];
const reportTypes=[["حادث","🚨"],["ازدحام","🚗"],["طريق مغلق","⛔"],["أعمال طريق","🚧"],["خطر","⚠️"]];
const key="waz-reports-v1";

function App(){const mapEl=useRef<HTMLDivElement>(null);const map=useRef<maplibregl.Map|null>(null);const user=useRef<maplibregl.Marker|null>(null);const dest=useRef<maplibregl.Marker|null>(null);const route=useRef<maplibregl.GeoJSONSource|null>(null);
const[query,setQuery]=useState("");const[results,setResults]=useState<any[]>([]);const[point,setPoint]=useState<Point|null>(null);const[userPos,setUserPos]=useState<Point|null>(null);const[status,setStatus]=useState("جاهز");const[loading,setLoading]=useState(false);const[nav,setNav]=useState(false);const[distance,setDistance]=useState(0);const[duration,setDuration]=useState(0);const[reports,setReports]=useState<Report[]>(()=>{try{return JSON.parse(localStorage.getItem(key)||"[]")}catch{return[]}});const[reportOpen,setReportOpen]=useState(false);const[reportType,setReportType]=useState(reportTypes[0][0]);const[note,setNote]=useState("");const[sound,setSound]=useState(true);const[online,setOnline]=useState(navigator.onLine);
useEffect(()=>{localStorage.setItem(key,JSON.stringify(reports))},[reports]);useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener("online",on);addEventListener("offline",off);return()=>{removeEventListener("online",on);removeEventListener("offline",off)}},[]);
useEffect(()=>{if(!mapEl.current)return;const style={version:8,sources:{osm:{type:"raster",tiles:["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],tileSize:256,attribution:"© OpenStreetMap contributors"}},layers:[{id:"osm",type:"raster",source:"osm"}]};const m=new maplibregl.Map({container:mapEl.current,style,center:IRAQ,zoom:5.2,maxZoom:19});m.addControl(new maplibregl.NavigationControl({showCompass:true}),"top-left");m.on("load",()=>{m.addSource("route",{type:"geojson",data:{type:"FeatureCollection",features:[]}});m.addLayer({id:"route-casing",type:"line",source:"route",paint:{"line-color":"#064e3b","line-width":9,"line-opacity":.85}});m.addLayer({id:"route",type:"line",source:"route",paint:{"line-color":"#14b8a6","line-width":5}});route.current=m.getSource("route") as maplibregl.GeoJSONSource});m.on("click",e=>{setPoint({lat:e.lngLat.lat,lon:e.lngLat.lng});});map.current=m;return()=>m.remove()},[]);
useEffect(()=>{if(!map.current)return;reports.forEach(r=>{const el=document.createElement("div");el.className="report-marker";el.textContent=reportTypes.find(x=>x[0]===r.type)?.[1]||"📍";new maplibregl.Marker({element:el}).setLngLat([r.lon,r.lat]).addTo(map.current!)})},[reports]);
const locate=useCallback(()=>{if(!navigator.geolocation){setStatus("GPS غير متاح");return}setStatus("جاري تحديد الموقع…");navigator.geolocation.getCurrentPosition(p=>{const q={lat:p.coords.latitude,lon:p.coords.longitude};setUserPos(q);setStatus("GPS نشط");if(!user.current)user.current=new maplibregl.Marker({color:"#2563eb"}).setLngLat([q.lon,q.lat]).addTo(map.current!);else user.current.setLngLat([q.lon,q.lat]);map.current?.flyTo({center:[q.lon,q.lat],zoom:16,duration:900})},()=>setStatus("تعذر الوصول إلى GPS"),{enableHighAccuracy:true,timeout:12000,maximumAge:5000})},[]);
const search=async()=>{if(!query.trim())return;setLoading(true);try{const u="https://nominatim.openstreetmap.org/search?format=jsonv2&limit=8&accept-language=ar&q="+encodeURIComponent(query);const r=await fetch(u,{headers:{"User-Agent":"WAZ-Iraq/1.0"}});setResults(await r.json());}catch{setStatus("فشل البحث — تحقق من الاتصال")}finally{setLoading(false)}};
const choose=(r:any)=>{const q={lat:+r.lat,lon:+r.lon,name:r.display_name};setPoint(q);setResults([]);map.current?.flyTo({center:[q.lon,q.lat],zoom:15,duration:900})};
const navigate=async()=>{if(!point)return;const origin=userPos||{lat:map.current?.getCenter().lat||IRAQ[1],lon:map.current?.getCenter().lng||IRAQ[0]};setLoading(true);try{const url=`https://router.project-osrm.org/route/v1/driving/${origin.lon},${origin.lat};${point.lon},${point.lat}?overview=full&geometries=geojson&alternatives=true&steps=true`;const r=await fetch(url);const j=await r.json();if(!j.routes?.[0])throw Error();const rt=j.routes[0];route.current?.setData({type:"FeatureCollection",features:[{type:"Feature",properties:{},geometry:rt.geometry}]});setDistance(rt.distance);setDuration(rt.duration);setNav(true);dest.current?.remove();dest.current=new maplibregl.Marker({color:"#dc2626"}).setLngLat([point.lon,point.lat]).addTo(map.current!);const b=new maplibregl.LngLatBounds();rt.geometry.coordinates.forEach((c:any)=>b.extend(c));map.current?.fitBounds(b,{padding:{top:140,bottom:180,left:30,right:30},duration:800});setStatus("الملاحة جاهزة")}catch{setStatus("تعذر حساب المسار")}finally{setLoading(false)}};
const addReport=()=>{if(!userPos){setStatus("حدد موقعك أولًا للإبلاغ");return}setReports(x=>[...x,{id:crypto.randomUUID(),lat:userPos.lat,lon:userPos.lon,type:reportType,note,time:Date.now()}]);setReportOpen(false);setNote("");setStatus("تم إرسال البلاغ محليًا")};
const fmtDist=(m:number)=>m>=1000?(m/1000).toFixed(1)+" كم":Math.round(m)+" م";const fmtTime=(s:number)=>Math.max(1,Math.round(s/60))+" دقيقة";
return <main><div ref={mapEl} className="map"/><div className="topbar"><div className="brand"><span>W</span><div><b>WAZ</b><small>خرائط العراق</small></div></div><div className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="ابحث عن مكان أو شارع…"/><button onClick={search}>{loading?"…":"بحث"}</button></div><div className="status"><i className={online?"ok":"bad"}/>{online?<Wifi size={15}/>:<WifiOff size={15}/>}<span>{status}</span></div></div>
{results.length>0&&<div className="results">{results.map(r=><button key={r.place_id} onClick={()=>choose(r)}><MapPin size={18}/><span><b>{r.name||r.display_name.split(",")[0]}</b><small>{r.display_name}</small></span></button>)}</div>}
<div className="actions"><button onClick={locate} title="موقعي"><LocateFixed/></button><button onClick={()=>setSound(!sound)} title="الصوت">{sound?<Volume2/>:<VolumeX/>}</button><button className="report" onClick={()=>setReportOpen(true)} title="إبلاغ"><AlertTriangle/></button></div>
{point&&!nav&&<section className="place"><button className="close" onClick={()=>setPoint(null)}><X/></button><MapPin/><div><b>{point.name||"الموقع المحدد"}</b><small>{point.lat.toFixed(5)}, {point.lon.toFixed(5)}</small></div><button className="go" onClick={navigate}><Navigation size={18}/> ابدأ</button></section>}
{nav&&<section className="navcard"><div className="navhead"><div><small>الوصول التقريبي</small><strong>{fmtTime(duration)}</strong></div><div><small>المسافة</small><strong>{fmtDist(distance)}</strong></div><button onClick={()=>{setNav(false);route.current?.setData({type:"FeatureCollection",features:[]});dest.current?.remove()}}><X/></button></div><div className="navhint"><Navigation/> اتبع المسار الأخضر إلى وجهتك <ChevronDown/></div></section>}
<div className="bottom"><div><CarFront/><span>WAZ<br/><small>ملاحة عراقية</small></span></div><div className="pills"><span><Clock3/> {reports.length} بلاغات محلية</span><span>OSM</span></div></div>
{reportOpen&&<div className="modal"><div className="dialog"><button className="close" onClick={()=>setReportOpen(false)}><X/></button><h2>إبلاغ عن الطريق</h2><p>سيتم ربط البلاغ بموقع GPS الحالي.</p><div className="types">{reportTypes.map(([t,e])=><button className={t===reportType?"sel":""} onClick={()=>setReportType(t)} key={t}>{e} {t}</button>)}</div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="ملاحظة اختيارية…"/><button className="primary" onClick={addReport}><AlertTriangle/> إرسال البلاغ</button></div></div>}</main>}
export default App;